lists:
  infinite:
    - TNT
    # All types of carpet
    - WHITE_CARPET
    - ORANGE_CARPET
    - MAGENTA_CARPET
    - LIGHT_BLUE_CARPET
    - YELLOW_CARPET
    - LIME_CARPET
    - PINK_CARPET
    - GRAY_CARPET
    - LIGHT_GRAY_CARPET
    - CYAN_CARPET
    - PURPLE_CARPET
    - BLUE_CARPET
    - BROWN_CARPET
    - GREEN_CARPET
    - RED_CARPET
    - BLACK_CARPET
    # All types of rail
    - RAIL
    - POWERED_RAIL
    - DETECTOR_RAIL
    - ACTIVATOR_RAIL
  expensive_infinite:
    - SAND
    - GRAVEL
    - WHITE_CONCRETE_POWDER
    - ORANGE_CONCRETE_POWDER
    - MAGENTA_CONCRETE_POWDER
    - LIGHT_BLUE_CONCRETE_POWDER
    - YELLOW_CONCRETE_POWDER
    - LIME_CONCRETE_POWDER
    - PINK_CONCRETE_POWDER
    - GRAY_CONCRETE_POWDER
    - LIGHT_GRAY_CONCRETE_POWDER
    - CYAN_CONCRETE_POWDER
    - PURPLE_CONCRETE_POWDER
    - BLUE_CONCRETE_POWDER
    - BROWN_CONCRETE_POWDER
    - GREEN_CONCRETE_POWDER
    - RED_CONCRETE_POWDER
    - BLACK_CONCRETE_POWDER

names:
  expensive_core: 无限核心
  expensive_core_partial: 残破的无限核心
